language: go

go:
  - 1.14.x

jobs:
  include:
    - stage: "Compile"
      name: "Compile Packages and Dependencies"
      script: go build -v
    - stage: "Tests"
      name: "Unit Tests"
      script: go test -v
    - stage: "Code Quality"
      name: "Code Quality Analysis"
      before_script:
        - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.30.0
      script: golangci-lint run -v